### ISSUE TITLE
More guidance needed to create users

### ISSUE THREAD

**Issue by jblakecoco** [rcastrucci/server-browser#1]
Hello, I like what you do. It's simple and kind of what I was looking for. As there is no proper documentation, would you be willing to provide additional context on how to create new users with access to only their folder?

Any help would be greatly appreciated. Thank you.

**Comment by rcastrucci** [comment]
Hi, @jblakecoco! It took me a little while to respond, I can only log here on weekends. This project is not yet finished, the idea would be once you sign as administrator you would be able to create new users directly on the page. But for now, if you want to create a new user, you will need to do by hand. Here are the steps:

Open the repo main directory edit the file .users.csv on terminal I usually use the vim editor, but you can use any text editors or even better some csv editor.

In this file you will see the first line written:

`client,folder,name,username,email,pass`

That is the structure of the data you need to input to create a new user. Just add a new line on the end of the file following the structure, each data needs to be separated by comma, so don't use comma's in any of the data you input. The folder data could be the absolute path or relative path that you wish to share with this user.
WARNING! BE CAREFUL WITH WHAT FOLDER YOU WILL SHARE.

The password you will need to add a hash SHA256 you can generate on terminal or on any website just like the one: https://emn178.github.io/online-tools/sha256.html

Example, to create a new user called John Smith, and share with him a folder called "john_files" located on the webpage folder and give him a username as johnsmith an a password as john, you need to write all in one single line as follows: 

`John Smith,./john_files,John Smith,johnsmitth,john@smith.com,96d9632f363564cc3032521409cf22a852f2032eec099ed5967c0d000cec607a`

That's it! The user johnsmith was created! To access just type johnsmith and password john

Hope that helps! Later on I will add a better documentation on the repo.
